// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZtdAOrfHzU-DG6mqL5H7vklya7BKTlg',
    appId: '1:439024886580:web:d3463de15106120db1fb61',
    messagingSenderId: '439024886580',
    projectId: 'bootcampmaterial-65677',
    authDomain: 'bootcampmaterial-65677.firebaseapp.com',
    storageBucket: 'bootcampmaterial-65677.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNHRhh1M9b4286ALqtYou6qS_g4_dBHM',
    appId: '1:439024886580:android:67136759acd2b8ddb1fb61',
    messagingSenderId: '439024886580',
    projectId: 'bootcampmaterial-65677',
    storageBucket: 'bootcampmaterial-65677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0H0ZKEOr4DBQqlvHyyI5Gl9nr1kxhULk',
    appId: '1:439024886580:ios:dcd778dbda7ff6fab1fb61',
    messagingSenderId: '439024886580',
    projectId: 'bootcampmaterial-65677',
    storageBucket: 'bootcampmaterial-65677.appspot.com',
    iosClientId: '439024886580-qmhpqb1dt51c2gm7c56bfourdtqt7pds.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0H0ZKEOr4DBQqlvHyyI5Gl9nr1kxhULk',
    appId: '1:439024886580:ios:dcd778dbda7ff6fab1fb61',
    messagingSenderId: '439024886580',
    projectId: 'bootcampmaterial-65677',
    storageBucket: 'bootcampmaterial-65677.appspot.com',
    iosClientId: '439024886580-qmhpqb1dt51c2gm7c56bfourdtqt7pds.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
